### ISSUE TITLE
box-sizing: borderbox is missing

### ISSUE THREAD

**Issue by geri777** [StefanoVollono/bootstrap-3-grid#1]
Does not work out of the box as `box-sizing: border-box` is missing for .col-*
After adding it in line 42 it works

**Comment by StefanoVollono** [comment]
Hi @geri777, inside project's readme i wrote an important note about box-sizing. This css includes only responsive grid utilities. Box-sizing management is delegated to the end user. Everyone prefers to insert and manage it differently based on the project he is working on. For this reason I decided not to insert it. I hope I have answered you.
